version: '3.7'

services:
  php:
    build: .
    volumes:
      - ./:/workdir
    tty: true
    environment:
      XDEBUG_CONFIG: client_host=$XDEBUG_REMOTE_HOST client_port=9000
      XDEBUG_MODE: develop,debug
      XDEBUG_TRIGGER: 1
      PHP_IDE_CONFIG: serverName=nemo-api
