#!/usr/bin/env php
<?php declare(strict_types=1);

use Spawnia\Sailor\Console\CodegenCommand;
use Spawnia\Sailor\Console\IntrospectCommand;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/../../autoload.php')) {
    // The usual location, since this file will reside in vendor/bin
    require __DIR__.'/../../autoload.php';
} else {
    // Useful when doing development on this package
    require __DIR__.'/vendor/autoload.php';
}

$console = new Application();

$addCommand = method_exists($console, 'addCommand')
    ? 'addCommand' // symfony/console 8
    : 'add'; // symfony/console 5-7

$codegenCommand = new CodegenCommand();
$console->$addCommand($codegenCommand);
$console->setDefaultCommand($codegenCommand->getName());
$console->$addCommand(new IntrospectCommand());

$console->run();
