name: "Autoformat"
on:
  push:
    branches:
      - '*'

jobs:
  composer-normalize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: mbstring
          php-version: 8.3

      - run: composer install --no-interaction --no-progress --no-suggest

      - run: composer normalize

      - run: git pull

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Normalize composer.json

  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: mbstring
          php-version: 8.3

      - run: composer install --no-interaction --no-progress --no-suggest

      - run: vendor/bin/php-cs-fixer fix

      - run: git pull

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes
