query ClientDirectiveQuery($value: Boolean!) {
    scalarWithArg @skip(if: true)
    twoArgs @include(if: $value)
}

fragment ClientDirectiveFragment on Query {
    twoArgs
}

query ClientDirectiveFragmentSpreadQuery($value: Boolean!) {
    ...ClientDirectiveFragment @skip(if: $value)
}

query ClientDirectiveInlineFragmentQuery($value: Boolean!) {
    ... on Query @skip(if: $value) {
        twoArgs
    }
}

query SkipNonNullable($value: Boolean!) {
    nonNullable @skip(if: $value)
}

query IncludeNonNullable($value: Boolean!) {
    nonNullable @include(if: $value)
}

fragment NonNullableFragment on Query {
    nonNullable
}

query SkipNonNullableFragmentSpread($value: Boolean!) {
    ...NonNullableFragment @skip(if: $value)
}

query SkipNonNullableNestedInlineFragment($value: Boolean!) {
    ... @skip(if: $value) {
        ... on Query {
            nonNullable
        }
    }
}

fragment MultipleNonNullableFragment on Query {
    nonNullable
    secondNonNullable: nonNullable
}

query SkipMultipleNonNullableFragmentSpread($value: Boolean!) {
    ...MultipleNonNullableFragment @skip(if: $value)
}

query SkipMultipleNonNullableInlineFragment($value: Boolean!) {
    ... on Query @skip(if: $value) {
        nonNullable
        secondNonNullable: nonNullable
    }
}

query SkipThenSelectNonNullable($value: Boolean!) {
    ... on Query @skip(if: $value) {
        nonNullable
    }
    nonNullable
}

query SkipFalseNonNullable {
    nonNullable @skip(if: false)
}

query IncludeTrueInlineFragmentNonNullable {
    ... on Query @include(if: true) {
        nonNullable
    }
}

query SkipFalseIncludeVariableNonNullable($value: Boolean!) {
    nonNullable @skip(if: false) @include(if: $value)
}
